### ISSUE TITLE
Spawn Video Feeds as users join through WebRTC

### ISSUE THREAD

**Issue by tlsharkey** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking#12]
Create new Video Feeds as participants join the call.

**Comment by siueric0010** [comment]
I believe this has been implemented via the addStreamer function call whenever a new consumer transport is created. However, we do need functionality for when they close. That means, on a close transport, we need a function that would remove the streamer.

**Comment by tlsharkey** [comment]
@tlsharkey implement closing feature #37
