### ISSUE TITLE
Implement WebRTC

### ISSUE THREAD

**Issue by tlsharkey** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking#18]

**Comment by siueric0010** [comment]
Example Code used:
https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms

**Comment by siueric0010** [comment]
webrtc_sfu_experiment is the experiemnt branch for webrtc. I will be using Dirvann's code a lot to implement meeting room functionality with webrtc. I got webRTC to work by using their code, but I will be going through the code and commenting through the entire code to understand how it works and if we really need all of the code.

**Comment by siueric0010** [comment]
TODO:
- [ ] Implement cleanup streamers when people leave the room.
- [ ] When another person leaves, clean up their streamer
- [ ] Implement streamers so that they don't overlap.
- [ ] When a person leaves a room, their streamers from past rooms should not be there.

**Comment by tlsharkey** [comment]
Implemented a bunch of these in the branch for #19 : [ticket-19_Avatars](https://github.com/WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking/tree/ticket-19_Avatars). I'm not sure exactly what they all mean, but they may all be done already.
- I hard coded the room to `118218` by default. We can add a virtual button later to change rooms if we want.
- videos spawn and are destroyed as users join and leave.
- I'm managing socket ids so I can relate audio and video even if there are multiples.

There's a little bug on the branch (about the order in which people join) after my last commit, once I fix that I'll merge it, but the code is stable if you want to look at it.

**Comment by siueric0010** [comment]
I see, I also implemented the stuff above in my own branch. I've also added the positioning of videos which took most of my time. I'll check out your code and see what conflicting code I can delete. Lmk when you merge the branch back into main so I can resolve conflicts and push my changes as well.

**Comment by siueric0010** [comment]
Also, my changes are not as big as yours, so it won't be as hard to resolve conflicts: #[ticket18-updating-streamers](https://github.com/WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking/tree/ticket18-updating-streamers)
