### ISSUE TITLE
Desktop Client Version

### ISSUE THREAD

**Issue by tlsharkey** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking#27]
There needs to be a separate version for desktop clients which shows a zoom-like interface

**Comment by tlsharkey** [comment]
@jgjo and @nrizvi can you design and implement this?

**Comment by jgjo** [comment]
**Requirements**
- Standalone web/html "zoom" window for web clients
- With video elements (have a placeholder that Eric can replace)
