### ISSUE TITLE
Phone Interaction

### ISSUE THREAD

**Issue by tlsharkey** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking#29]
User needs to be able to raycast from the phone and select elements in the XR space

**Comment by tlsharkey** [comment]
My phone doesn't have a good enough processor to render the scene well so I can't tell if things are working or not. I will be leaving this for someone else.

**Comment by siueric0010** [comment]
![image](https://user-images.githubusercontent.com/22266184/100537147-d6203a80-31da-11eb-970d-c4a0172ebf0d.png)
^ first connection to webpage
![image](https://user-images.githubusercontent.com/22266184/100537154-e506ed00-31da-11eb-8dde-f89a4809c451.png)
^ first time clicking on the webxr icon on the bottom right (notice that there's no control panel for the first click)
![image](https://user-images.githubusercontent.com/22266184/100537164-f94aea00-31da-11eb-99d9-cb2720163315.png)
^ how it looks when i exit the webxr view
![image](https://user-images.githubusercontent.com/22266184/100537169-023bbb80-31db-11eb-8fae-beba43f909f7.png)
^ how it looks when i return to the webxr view (the control panel is back)

**Comment by siueric0010** [comment]
Overall, there are two issues I saw:
1. when I first enter the VR view that the control panel does not show.
2. when I enter after the first time, the control panel does not rotate with the phone. So, the control panel is vertical when it should be horizontal.
