### ISSUE TITLE
Zoom integration

### ISSUE THREAD

**Issue by tlsharkey** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_SRSLy_Joking#7]
Explore the [Zoom API for streaming](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to see if we can use zoom instead of WebRTC

**Comment by tlsharkey** [comment]
Explore the [Zoom API for streaming](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to see if we can use zoom instead of WebRTC

**Comment by siueric0010** [comment]
Left some notes on the teams chat. The TLDR: We can use zoom if it means that our avatars are somewhat lifeless and the only way we can tell someone is talking is whether their mic is muted or not. (meaning no webcam videos at the same time).

**Comment by tlsharkey** [comment]
I looked into Google Meets, and their API has even less. We'll bring this up tomorrow morning in our meeting and decide what to do.
